### ISSUE TITLE
Player does not play video and show blank screen when enter full screen

### ISSUE THREAD

**Issue by satyamub** [rtoshiro/FullscreenVideoView#1]
Hi I am using this control. when I try to enter full screen, it goes blank with random time on right hand side(which is I guess Estimated time of video) then when I come back from full screen it also shows the blank screen>

Help me out

**Comment by rtoshiro** [comment]
Hi
When you call setVideoPath or setVideoURI, what happens? Did it show anything in LogCat?

**Comment by satyamub** [comment]
I used setVideoURI. in all cases 

setDataSource: IOException! uri=http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4

**Comment by satyamub** [comment]
But that does not crash cause its embed in try catch and play starts playing however, when I enter into full screen it shows blank screen and if I exit, it also stops in small
screen. This happens when play button is on

08-12 11:10:14.267  22686-22686/com.satya.myvideoview E/MediaPlayer﹕ start called in state 0
08-12 11:10:14.267  22686-22686/com.satya.myvideoview E/MediaPlayer﹕ error (-38, 0)
08-12 11:10:14.277  22686-22686/com.satya.myvideoview E/MediaPlayer﹕ Error (-38,0)

**Comment by satyamub** [comment]
cam i send you project?

**Comment by satyamub** [comment]
![screenshot_2015-08-12-13-38-06](https://cloud.githubusercontent.com/assets/13571747/9219777/ce1ae140-40fa-11e5-80a5-4bc04bf8d760.png)
![screenshot_2015-08-12-13-38-30](https://cloud.githubusercontent.com/assets/13571747/9219776/ce186a78-40fa-11e5-9d7b-d63394827fd0.png)
![screenshot_2015-08-12-13-39-10](https://cloud.githubusercontent.com/assets/13571747/9219778/ce1d3ba2-40fa-11e5-89cb-de6e79a78df3.png)

**Comment by rtoshiro** [comment]
Sure. Can you send me a link to download your project?

**Comment by satyamub** [comment]
https://www.dropbox.com/s/cemxtterbz8oe4p/MyVideoTwo.zip?dl=0

When the player starts, without pausing, click on the fullscreen and it will go black after that , no one would be able to play/pause. Some times, it shows weird expected time as well.

**Comment by rtoshiro** [comment]
I still cannot see the problem :( even with your project.
Which version of Android OS are you testing it? I'll try to test with the same version.
In parallel, I've just released a new version 1.0.3.

**Comment by rtoshiro** [comment]
Hi @satyamub 
Did you get it work?

**Comment by satyamub** [comment]
Hi rtoshiro, 
I am building using 22 and I am testing it on Kitkat

**Comment by rtoshiro** [comment]
@satyamub 
I'm having same problem here now testing on Kitkat 4.4.4 
It woks with 4.1 and 5. But 4.4 is very buggy. I'm trying to fix it but I think I'll have to change a bit litle more.
I'll keep you in touch.

**Comment by ErfanThinker** [comment]
here's the fix:(in FullScreenVideoLayout.java:249)

if (isPlaying()) {
                pause();
                fullscreen();
                new Handler().post(new Runnable() {
                    @Override
                    public void run() {
                        start();
                    }
                });
            } else {
                fullscreen();
            }

**Comment by rtoshiro** [comment]
@ErfanThinker It doesn't work here as expected. This way FullScreenVideoLayout will call fullscreen() everytime user clicks play/pause button.
Do you know which case "isPlaying()" is not working? I've tested it here and apparently it is ok.

**Comment by ErfanThinker** [comment]
No, let me give you full code:

   @Override
    public void onClick(View v) {
        if (v.getId() == R.id.vcv_img_play) {
            if (isPlaying()) {
                pause();
            } else {
                start();
            }
        } else {
            if (isPlaying()) {
                pause();
                fullscreen();
                new Handler().post(new Runnable() {
                    @Override
                    public void run() {
                        start();
                    }
                });
            } else {
                fullscreen();
            }
        }
    }

sorry I don't know how to align code in github.
Oh sorry, isPlaying() works, I had paused it before that's why I thought it doesn't work, however your code didn't work for me. I tried my code on my nexus 5 with android 5.0 and also android 4.1 and also kitkat (on emulator) and it worked without problems.

**Comment by rtoshiro** [comment]
@ErfanThinker Ah, ok. Thank you. I'm going to update here or you can push a pull request if you prefer.
thank you.
