### ISSUE TITLE
how can i change the controller after change fullscreen?

### ISSUE THREAD

**Issue by ehaahe** [rtoshiro/FullscreenVideoView#11]

**Comment by rtoshiro** [comment]
Hi @ehaahe 
Well, if you are using FVVLayout, you can access "videoControlsView" and manipulate all subviews programmatically. Another way is to create another layout XML for your new "fullscreen controller", and inflate and add inside FVVLayout. Then, you can hide/show in setFullscreen() method.
I hope it helps.
Best
T

**Comment by rtoshiro** [comment]
Closing it due to lack of interaction.
