### ISSUE TITLE
Not supporting for youtube video link

### ISSUE THREAD

**Issue by mahesh825mahi** [rtoshiro/FullscreenVideoView#12]
It's not supporting for Youtube video link.

**Comment by rtoshiro** [comment]
Hi @mahesh825mahi 
Well, unfortunately this problem it is not related to FullscreenVideoView as It supports everything that native VideoView supports.
Usually, the native VideoView should receive a RTSP video link directly to work with YouTube.
As it is not easy to get the video link from YouTube link, I recommend you to play YouTube links using WebView or YouTube Android SDK API.
http://stackoverflow.com/questions/4654878/how-to-play-youtube-video-in-my-android-application
http://stackoverflow.com/questions/8148535/media-player-using-youtube
Hope it helps.
Best
T
