### ISSUE TITLE
Support screen orientation change

### ISSUE THREAD

**Issue by HamidrezaAmz** [rtoshiro/FullscreenVideoView#13]
hi
On screen orientation change activity stock in a loop of refreshing view. I think this is a bug in videoview, I every tutorials and libraries I found this problem, is there any solution?

**Comment by rtoshiro** [comment]
Hi @HamidrezaAmz 
What kind of refreshing loop? Are you implementing onConfigurationChanged method? Are you calling videoview.resize()?
Would you mind passing me more information about how can I achieve this issue? So I can see how can I help you.
Thanks.

**Comment by HamidrezaAmz** [comment]
Hi @rtoshiro 
Every thing is OK until I force the screen to be in landscape mode, I test all suggested solutions on stack-overflow about handling orientation change bud nothing achieved!  My activity stuck in a loop of calling onDestroy and onCreate Continuously. Do you have any idea!
Thanks.

**Comment by HamidrezaAmz** [comment]
Hi @rtoshiro 
I found the solution, I was overriding configuration method in my main application class. the new config was the problem.
have fun, thanks.
