### ISSUE TITLE
How to start video automatically

### ISSUE THREAD

**Issue by kriztan** [rtoshiro/FullscreenVideoView#15]
Hi,
great job! But can you tell me, how I could start a video automatically without modifying your source?
Thanks

**Comment by rtoshiro** [comment]
hi @kriztan 
Well, you can call setShouldAutoplay(true) or call start() after setting video path. I think both will do the job ;)
Thanks

**Comment by kriztan** [comment]
Hi @rtoshiro 
`setShouldAutoplay(true)` does the trick. 
Thanks a lot.
