### ISSUE TITLE
Can't get it to play live streaming video

### ISSUE THREAD

**Issue by JosephSKh** [rtoshiro/FullscreenVideoView#17]
Hello, I can't make the player play a live streaming video

the type is .f3m or .m3u8

does it support that?

Thanks

**Comment by satyamub** [comment]
@JosephSKh you can use MPMovieplayerController/AvPlayer for m3u8 extension in iOS and in android Android Media Player API

**Comment by JosephSKh** [comment]
@satyamub .. thank you for your reply .. but do those players have a full screen button? .. my main reason for using this is the configurable layout and the fullscreen button
Thank you

**Comment by rtoshiro** [comment]
Hi @JosephSKh 
Well, it was built on top of MediaPlayer so FullscreenVideoView should play every video that MediaPlayer or VideoView handles.
Can you play this stream using native VideoView?
Do you know which codec was used to compress this stream?

**Comment by JosephSKh** [comment]
Hello @rtoshiro .. thank you for your reply
Yes I'm able tp play it on a normal vidro view .. but in this one it just keeps loading .. although I've tried the .mp4 birds video you pit in the sample
mmm I'm not sure of the second question's answer .. but if you mean the type .. then it's m3u8 and f3m

**Comment by rtoshiro** [comment]
Hi @JosephSKh 
I have found a bug about video width/height not setting it correctly but I don't think it is related to your problem as it keeps loading indefinitely.
Is that url public? Or do you have another url sample (that works on native VideoView) to share so I can test it here?

**Comment by JosephSKh** [comment]
Hello @rtoshiro 
Yes, here's the link I'm using
http://media.smc-host.com:1935/cycnow.com/smil:cyc.smil/playlist.m3u8

**Comment by rtoshiro** [comment]
mmm, I have tested it and it works with this last bug fix. 
In fact, it worked in a Sansung S3 with 4.3 and worked in a Custom 6.0. 
But not worked in a Custom Genymotion 4.1.1, but in that case, native VideoView did not work neither.
As you said that it worked in native VideoView, would you mind testing it with the last version?

```
compile 'com.github.rtoshiro.fullscreenvideoview:fullscreenvideoview:1.1.1d-SNAPSHOT'
```

Just remember to include the repository because it is in a release-beta version:

```
allprojects {
    repositories {
        jcenter()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}
```

**Comment by JosephSKh** [comment]
@rtoshiro It's still not working, Am I missing sth?
The log says

> E/MediaPlayer: start called in state 0

does it mean anything?
Thank you.

**EDIT**
I'm using a Nexus 5 with 6.0.1

**Comment by rtoshiro** [comment]
It seems the code is calling start() before the state is prepared.
Would you mind sharing the piece of code you are using to instantiate and starting the FullscreenVideoView?

**Comment by JosephSKh** [comment]
Sure..
adding the URL to the video view

creating Video object
in onCreate
`myVideoView = (FullscreenVideoLayout)this.findViewById(R.id.myVideo);
`
InitVideo is called from AsyncTask that gets the url from the json got from the service

`public void InitVideo(String url) {
        FABRefresh.setVisibility(View.INVISIBLE);
        urlStream = url;
        try {
            myVideoView.setVideoURI(Uri.parse(urlStream));
        }catch(IOException e){}
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                    isStreaming = false;
            }
        });
    }`

**EDIT**
url is sent from the asynctask

**EDIT2**
I even tried to hardcode the streaming m3u8 link

**Comment by rtoshiro** [comment]
Mmm.. Now that is bizarre. I have tested with the same device Nexus 5 (6.0.1).
Would you mind trying to make a little test?
Just move the setVideoURI() part to onCreate() and put your static URL like the code below, and set setAutoplay to true:

``` java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        myVideoView = (FullscreenVideoLayout) findViewById(R.id.myVideo);
        myVideoView.setShouldAutoplay(true);
        Uri videoUri = Uri.parse("http://media.smc-host.com:1935/cycnow.com/smil:cyc.smil/playlist.m3u8");
        try {
            myVideoView.setVideoURI(videoUri);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

```

And if not works, can you copy and paste the stacktrace error from Android Monitor?

**Comment by JosephSKh** [comment]
@rtoshiro Oh great it's working !
Thanks man, may I know what's wrong then?

**Comment by rtoshiro** [comment]
Do you know from which method of AsyncTask are you calling **_InitVideo()**_ ?
doInBackground? onProgressUpdate? onPostExecute?

**Comment by JosephSKh** [comment]
onPostExecute
shows 
java.lang.IllegalStateException: FullscreenVideoView Invalid State: PLAYBACKCOMPLETED

do in background ,,, keeps infinite loading

**Comment by rtoshiro** [comment]
Do you know if are other callings of initVideo() in the code?
Well, considering you are getting the URL from the service in doInBackground, the recommended place to call initVideo is in onPostExecute, because it happens in UI thread.
If you keep the setShouldAutoplay(true):

``` java
myVideoView = (FullscreenVideoLayout)this.findViewById(R.id.myVideo); 
myVideoView.setShouldAutoplay(true);
```

 and call only the setVideoURI() in initVideo() like the code below?:

``` java
public void InitVideo(String url) {
        try {
            myVideoView.setVideoURI(Uri.parse(url));
        } catch (IOException e) {
        }
}
```

Considering calling initVideo() from onPostExecute.

**Comment by JosephSKh** [comment]
yup, that's exactly what I'm doing now.

> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                     Process: com.cyc.joseph.cyc, PID: 27078
>                                                                     java.lang.IllegalStateException: FullscreenVideoView Invalid State: PLAYBACKCOMPLETED
>                                                                         at com.github.rtoshiro.view.video.FullscreenVideoView.setVideoURI(FullscreenVideoView.java:808)
>                                                                         at com.cyc.joseph.cyc.MainActivity.InitVideo(MainActivity.java:148)
>                                                                         at com.cyc.joseph.cyc.MainActivity$CYCAsyncTask.onPostExecute(MainActivity.java:737)
>                                                                         at com.cyc.joseph.cyc.MainActivity$CYCAsyncTask.onPostExecute(MainActivity.java:692)
>                                                                         at android.os.AsyncTask.finish(AsyncTask.java:651)
>                                                                         at android.os.AsyncTask.-wrap1(AsyncTask.java)
>                                                                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
>                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                         at android.os.Looper.loop(Looper.java:148)
>                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                         at java.lang.reflect.Method.invoke(Native Method)
>                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**EDIT**
There are no any other calls for **InitVideo**

**Comment by rtoshiro** [comment]
mmm.. there is something I'm missing in the code because FullscreenVideoView should not be in PLAYBACKCOMPLETED before setVideoURI() is called.
Do you know if initVideo() is called more than once? (adding a Log.i("", "called") or breakpoint inside InitVideo() to see if it called more than one time)
Considering the only place you call setVideoURI is inside initVideo.

**Comment by JosephSKh** [comment]
hmmm, IDK, but anyway it's only called from the **asynctask** in **postexecute**,,
and I think that shouldn't happen anyway as the native **VideoView** was working smoothly
and yes i'm only setting the uri in the **initvideo**
Anyway I think I will keep digging for the problem a bit as it's working in the **oncreate**,, Will keep you updated, Thank you so much @rtoshiro for your GREAT help

**Comment by JosephSKh** [comment]
@rtoshiro Okay, it's solved now, thank you Man :)
The problem is that .start() was being called somehwere in **onResume()**

Thank you again dude

**Comment by rtoshiro** [comment]
Oh, nice!!
Good to know.
