### ISSUE TITLE
Hide progress spinner

### ISSUE THREAD

**Issue by Fred117** [rtoshiro/FullscreenVideoView#18]
Hello, 

first of all thank you very much for developing the FullscreenVideoView. :) I'm using it in my project and it helped a lot. But I would like to hide the red progress spinner to show a custom spinner while loading the video. For now I'm using a black view over the FullscreenVideoView so that the red spinner is not visible. But that's not the solution I'm looking for. ;) Would it be possible so give the FullscreenVideoView a method to hide the progress spinner?

**Comment by rtoshiro** [comment]
Hi @Fred117 
Thank you for using it. You are right.
I'm going to expose the access to the loading view in next release.

For a while, you can just subclass FullscreenVideoView and access **loadingView** property and hide it, Or, you can access the protected method called **stopLoading()**.

For your solution, to avoid internal problems, I recommend override **startLoading()** method to do nothing. So progressView is never started.

I hope it helps.
Best regards
T

**Comment by Fred117** [comment]
Hello, for now I have subclassed FullscreenVideoView but it would be great, if you would implement this feature in the next release. :)

**Comment by rtoshiro** [comment]
Hi @Fred117 
I have implemented a method called setOnProgressView() to overwrite the default progress view.
Thank you very much.
It will be available in next release.
Best

**Comment by Fred117** [comment]
Thank you very much. When are you going to release the new version?

**Comment by rtoshiro** [comment]
Hi @Fred117 
I have just released a new version ;)
Thx
Best

**Comment by Fred117** [comment]
Hello, 
I have implemented it now and it is much better. :) However, the red loading spinner is still shown for one second. :/
