### ISSUE TITLE
Is possible use FullscreenVideoView inner ScrollView??

### ISSUE THREAD

**Issue by renekaigen** [rtoshiro/FullscreenVideoView#21]
Hello, I´m trying to put the FullscreenVideoView on Scrollview but when I run the app , the fullscrenvideoview is really small and the scroll didnt works. What can I do ?

This is my xml 

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:id="@+id/relativeMain"
    android:orientation="vertical"
    >

```
<ScrollView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
  >

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">
```

```
<TextView
    android:id="@+id/tvNameChapter"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    />

<Spinner
    android:id="@+id/spKindOfPlayer"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    />

<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    >

    <aplicaciones.paleta.animex.FullscreenVideoLayout
        android:id="@+id/videoview"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"

        />
</FrameLayout>


<include layout="@layout/part_fragment_options" />

<TextView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="Hola que ace"/>

<Button
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="ajskdljasldk"/>

    </LinearLayout>
</ScrollView>
```

</LinearLayout>

**Comment by rtoshiro** [comment]
Hi @renekaigen 
Sorry for the delay. I think it cannot infer the video height properly as you have set it to wrap_content.
Maybe you can listen for ViewTreeObserver.OnGlobalLayoutListener to get the final width and set the height following the desired aspect ratio. I think I have already develop something like that to make my View's size dynamically.
I will look if it can happens inside FullscreenVideoView but I think it is better that this control is implemented outside it.
Tell me if you want some help to implement that solution. 
Best
T
