### ISSUE TITLE
found play bug & fullscreen bug

### ISSUE THREAD

**Issue by changhoonyang** [rtoshiro/FullscreenVideoView#22]
hi, I found 2 bug.

A. fullscreen issue.

step 1 : prepare video. click fullscreen button.
step 2 : click play button.

then onError callback.
but normal play mode is working.

B. playback issue.

step 1 : play video. 
step 2 : scroll to end of file.
step 3 : wait couple of second.
step 4 : seekbar scroll to.

then play error.

video is youtube file. 

Uri videoUri = Uri.parse("rtsp://r5---sn-oguesnzs.googlevideo.com/Cj0LENy73wIaNAm-0B8sPQIk6RMYDSANFC1oCLRXMOCoAUIASARgrrrYhZK_wJtWigELaUZ1RTZxckhTQ0UM/7838CAEC350073DF0D83C0F4E8886007EC4BDCC9.963DB937BB4245D1C4E330FF554CDEA8564A181A/yt6/1/video.3gp");

**Comment by rtoshiro** [comment]
Hi @changhoonyang 
Do you have the stacktrace related to both bugs?
I have tried to simulated the first bug  but apparently it can be a problem related to calling start methods in wrong state. 
The second one, I'm still trying to simulate. Your stacktrace would be very helpfull.
Best
T

**Comment by changhoonyang** [comment]
Hi, @rtoshiro 

could you let me know your email address?

I will send the test video file by e-mail to you.

error log is just like this.

---

08-22 15:47:21.124 11432-11442/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: callback application
08-22 15:47:21.124 11432-11442/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: back from callback
08-22 15:47:21.144 11432-11597/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: message received msg=6, ext1=0, ext2=0
08-22 15:47:21.144 11432-11597/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: Received MEDIA_STARTED
08-22 15:47:21.144 11432-11597/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: callback application
08-22 15:47:21.144 11432-11597/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: back from callback
08-22 15:47:21.144 11432-11597/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: message received msg=200, ext1=702, ext2=0
08-22 15:47:21.144 11432-11432/com.github.rtoshiro.example.fvvapplication V/MediaPlayer-JNI: getCurrentPosition: 0 (msec)
08-22 15:47:21.144 11432-11432/com.github.rtoshiro.example.fvvapplication E/MediaPlayer: internal/external state mismatch corrected
08-22 15:47:21.144 11432-11432/com.github.rtoshiro.example.fvvapplication V/MediaPlayer-JNI: isPlaying: 0
08-22 15:47:21.154 11432-11597/com.github.rtoshiro.example.fvvapplication W/MediaPlayer: info/warning (702, 0)
08-22 15:47:21.154 11432-11597/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: callback application
08-22 15:47:21.154 11432-11597/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: back from callback
08-22 15:47:21.154 11432-11597/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: message received msg=100, ext1=1, ext2=-19
08-22 15:47:21.154 11432-11432/com.github.rtoshiro.example.fvvapplication D/FullscreenVideoView: onInfo 702
08-22 15:47:21.154 11432-11597/com.github.rtoshiro.example.fvvapplication E/MediaPlayer: error (1, -19)
08-22 15:47:21.154 11432-11597/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: callback application
08-22 15:47:21.154 11432-11597/com.github.rtoshiro.example.fvvapplication V/MediaPlayer: back from callback
08-22 15:47:21.154 11432-11432/com.github.rtoshiro.example.fvvapplication E/MediaPlayer: Error (1,-19)

---

this is vedio source

---

Uri.parse("rtsp://r5---sn-oguesnzs.googlevideo.com/Cj0LENy73wIaNAm-0B8sPQIk6RMYDSANFC1oCLRXMOCoAUIASARgrrrYhZK_wJtWigELaUZ1RTZxckhTQ0UM/7838CAEC350073DF0D83C0F4E8886007EC4BDCC9.963DB937BB4245D1C4E330FF554CDEA8564A181A/yt6/1/video.3gp");

---

**Comment by rtoshiro** [comment]
Hi @changhoonyang 
My email is my username followed by @printwtf.com 
I make my email public in my profile.

In the meantime, have you already tested your code using the native VideoView?

**Comment by rtoshiro** [comment]
Hi @changhoonyang 
Please warn me when you send the email. 
Thank you.
Best

**Comment by changhoonyang** [comment]
hi, @rtoshiro 
Sorry. I'm late.
Sent to your Email.

Thank you.

**Comment by rtoshiro** [comment]
I lost track of this thread.
Plz, feel free to comment again.
