### ISSUE TITLE
hideControls not working

### ISSUE THREAD

**Issue by saadnawaz1** [rtoshiro/FullscreenVideoView#24]
Hi,

I want to hide the controls (pause button, progress bar and full screen button) when the video is playing. I tried setting hideControls upon the initialization of the object but that didn't work. Then i even tried it after start i.e. 

myVideoView.start();
myVideoView.hideControls();

but even with this the controls are shown. What am i doing wrong here?

**Comment by rtoshiro** [comment]
Hi @saadnawaz1 
Have you customize your videoControlsView? Are you calling start() and hideControls() from another thread?
Maybe the easiest solution is overriding start() method and call super.start() and then super.hideControls()

**Comment by saadnawaz1** [comment]
No I haven't customized videoControlsView ... and I am not calling start / hideControls from another thread.. both are called on UI thread.. 

I even tried overriding the start method and calling super.start and then super.hideControls(), but even that's not working ..

**Comment by rtoshiro** [comment]
Sorry. I remember we spoke about it, don't we?
Well. Please, comment again if you still have the problem.
