### ISSUE TITLE
Seekbar issue for online streaming

### ISSUE THREAD

**Issue by ketkipawar** [rtoshiro/FullscreenVideoView#27]
Hi,
For online streaming, if i drag seekbar further, player stops, while it works well for Offline videos.

**Comment by rtoshiro** [comment]
@ketkipawar 
Yes and no :)
In fact, the problem is that MediaPlayer only supports seekbar if the server supports it as well.
Can you test the same video using native VIdeoView player with controls?

**Comment by rtoshiro** [comment]
Closing due to lack of response.
