### ISSUE TITLE
Not support .mov file using URI

### ISSUE THREAD

**Issue by jays95jp** [rtoshiro/FullscreenVideoView#28]
i try to load video with .mov formate but not able to load video

**Comment by jays95jp** [comment]
get following error

> E/MediaPlayer: error (1, -2147483648)
>  E/MediaPlayer: Error (1,-2147483648)
> D/FullscreenVideoView: onError called - 1 - -2147483648
> D/FullscreenVideoLayout: stopCounter

also get this error

> E/MediaPlayer: Error (-38,0)
> D/FullscreenVideoView: onError called - -38 - 0
> D/FullscreenVideoLayout: stopCounter
> D/FullscreenVideoLayout: onCompletion
> D/FullscreenVideoLayout: stopCounter

**Comment by rtoshiro** [comment]
Hi @jays95jp 
Did you try using native VideoView to play the same video? 
Because, as FFView is a container to MediaPlayer, it should play everything native VideoView plays (only).
I'm going to try to find the specs for .mov files.

**Comment by rtoshiro** [comment]
I'm closing it due to lack of information.
