### ISSUE TITLE
Video (loaded from URL) thumbnail loading into an imageView  android Library

### ISSUE THREAD

**Issue by huxaiphaer** [rtoshiro/FullscreenVideoView#29]
Is there a simple android  library (like Picasso , Glide ) which  loads a Video from a URL into an ImageView , without it being downloaded , for instance like in a RecyclerView. I have tried to make research , but its still challenging on my side.

But for Glide it shoes thumbnails of local Videos in the phone but not URLs

**Comment by rtoshiro** [comment]
Hi @huxaiphaer 
Yeah, that is something really annoying. Android doesn't provide a nice thing regards to video thumbnail. At least for old versions. 
I think there are some codes at Google to get the image thumb from video and I'm still not convinced that is the best way and that I have to put it on the lib.
I don't know any lib for that but I remember there are a bunch of codes. But, yes, not easy way to make it work...
Feel free to comment again.
Best
H
