### ISSUE TITLE
Video thumbnail into the ImageView + Recyclerview(Using URLs)

### ISSUE THREAD

**Issue by huxaiphaer** [rtoshiro/FullscreenVideoView#30]
Is there any simple  android library which can load a Video thumbnail into an ImageView  from a URL like Picasso or Glide , when the Video is in the RecyclerView , and it just shows the thumbnail without downloading it.

But for Glide it loads thumbnails of local Videos in the phone not URLs

**Comment by rtoshiro** [comment]
Same question ;) #29
