### ISSUE TITLE
Video autostart

### ISSUE THREAD

**Issue by Gob-Lin** [rtoshiro/FullscreenVideoView#31]
Hello,

how can I play video as soon as it's loaded, without pressing the play button?
I have tried videoLayout.start() but it doesn't work.

Thank you,

P

**Comment by rtoshiro** [comment]
Hi @HeliosDev 
You can set the autoplay before setting the video :)
setShouldAutoplay(boolean)

**Comment by Gob-Lin** [comment]
Now that's what I call "fast support"!
Thank you rtoshiro!

P

**Comment by rtoshiro** [comment]
Thx ;)
