### ISSUE TITLE
Can I avoid the restart of the video after orientation change?

### ISSUE THREAD

**Issue by hanwel** [rtoshiro/FullscreenVideoView#32]
Hi,
on any orientation state, the video starts new from the beginning. This should not be a big issue, but I am playing an array of videos (with reloading the next url on every completion), and if the second video is showing and the orientation is changing, the first video is starting again.
Any ideas?
Thanks,
Hanno

**Comment by rtoshiro** [comment]
Hey @hanwel 
Yes, but usually you have to implement the orientation change:
```
@Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        videoLayout.resize();
}
```
In addition, you have to add android:configChanges on manifest.
You can see it here: https://github.com/rtoshiro/FullscreenVideoView/blob/master/fvvapplication/src/main/AndroidManifest.xml
