### ISSUE TITLE
i'm getting ProtocolException

### ISSUE THREAD

**Issue by inbox-nisar** [rtoshiro/FullscreenVideoView#33]
some videos play fine but i think on heigh resulation i'm getting this error if anyone know solution please let me know thanks 
W/MediaHTTPConnection: readAt 44734642 / 32768 => java.net.ProtocolException

**Comment by rtoshiro** [comment]
Hi @inbox-nisar 
Well, I think it is usually when the player doesn't know how to decode the video.
https://developer.android.com/guide/topics/media/media-formats.html
If you use the native VideoView, does it work?
