### ISSUE TITLE
In full screen mode, items on background are klicking

### ISSUE THREAD

**Issue by Monster-king** [rtoshiro/FullscreenVideoView#35]
In full screen mode, i'm clicking on the video Layout and items which on the background (not visible) are clicking.
![screenshot_2017-02-27-19-14-30](https://cloud.githubusercontent.com/assets/18480424/23364823/68f27888-fd22-11e6-89d3-569a793f31f3.png)
![screenshot_2017-02-27-19-14-23](https://cloud.githubusercontent.com/assets/18480424/23364832/708430d2-fd22-11e6-8903-e46b2ecc749c.png)

**Comment by rtoshiro** [comment]
Mmm.. that is weird.
I'll check :)

**Comment by rtoshiro** [comment]
Hi @Monster-king 
So, the "problem" is because we return "false" in our internal onTouchListener implementation.
The easiest way to solve it, it just set the onTouchListener and return true. 
view.setOnTouchListener...

**Comment by ka822** [comment]
I am having the same issue, but I am not sure where to set the view.setOnTouchListener(true);?
