### ISSUE TITLE
Video not opening in full screen when device rotate in Landscape

### ISSUE THREAD

**Issue by deepakcipl** [rtoshiro/FullscreenVideoView#5]
Hi,

Thanks for your wonderful code. I am facing a problem while playing video in landscape mode. Suppose video is playing in portrait mode and I pressed full screen button, now when I rotate the device in landscape mode, Video not stretched in full screen. I am using this code in fragment. How can I achieve this. Please help..

manifest file :- 
<activity
            android:name=".ui.activity.MainActivity"
            android:configChanges="orientation|screenSize"

```
        android:windowSoftInputMode="adjustPan"
        android:theme="@android:style/Theme.NoTitleBar.Fullscreen"/>
```

XML file :-1: 

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clickable="true"
    android:orientation="vertical">

    <FrameLayout
        android:id="@+id/framePros"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent">

        <com.rsi.talentfirstmeet.ui.widget.FullscreenVideoLayout
            android:id="@+id/videoView"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:layout_gravity="center_vertical"
            android:gravity="center" />
    </FrameLayout>

    <ooo.oxo.library.widget.TouchImageView
        android:id="@+id/img"
        android:layout_width="match_parent"
        android:layout_height="fill_parent"
        android:layout_gravity="center" />

    <com.joanzapata.pdfview.PDFView
        android:id="@+id/pdfview1"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <WebView
        android:id="@+id/webView1"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />


</LinearLayout>

<TextView
    android:id="@+id/empty_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center"
    android:textColor="@color/text_black"
    android:textSize="@dimen/text_large"
    android:visibility="gone" />
```

</RelativeLayout>

**Comment by rtoshiro** [comment]
Hi @deepakcipl 
I've released a new version 1.0.6 fixing this problem.
Can you confirm if it works?
Thank you.

**Comment by deepakcipl** [comment]
Sure.. Let me try this..

Thanks for your quick response :)

**Comment by deepakcipl** [comment]
Hi rtoshiro,
Its not working yet. Same problem exist.

**Comment by rtoshiro** [comment]
Hi @deepakcipl 
Thank you. Do you know which Android version are you testing it?

**Comment by deepakcipl** [comment]
Hi rtoshiro,
Actually, Demo is working fine but when I am implementing in my project. Landscape video is not opening in full screen. I am showing the video in fragment. 

XML file :

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clickable="true"
    android:orientation="vertical">

    <FrameLayout
        android:id="@+id/framePros"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent">

        <com.rsi.talentfirstmeet.ui.widget.FullscreenVideoLayout
            android:id="@+id/videoView"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:layout_gravity="center_vertical"
            android:gravity="center" />
    </FrameLayout>

    <ooo.oxo.library.widget.TouchImageView
        android:id="@+id/img"
        android:layout_width="match_parent"
        android:layout_height="fill_parent"
        android:layout_gravity="center" />

    <com.joanzapata.pdfview.PDFView
        android:id="@+id/pdfview1"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <WebView
        android:id="@+id/webView1"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />


</LinearLayout>

<TextView
    android:id="@+id/empty_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center"
    android:textColor="@color/text_black"
    android:textSize="@dimen/text_large"
    android:visibility="gone" />
```

</RelativeLayout>

Manifest file 

<application
        android:name=".TalentFirstMeetApplication"
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".ui.activity.MainActivity"
            android:configChanges="orientation|screenSize"
            android:screenOrientation="portrait"

```
      />
```

Fragment code 

```
private void showVideo(final String url){
    new Handler().postDelayed(new Runnable() {

        @Override
        public void run() {
        video.setActivity(getActivity());
        video.setShouldAutoplay(true);
        //Uri videoUri = Uri.parse("http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4");
        Uri videoUri = Uri.parse(url);
            try {
                video.reset();
                video.hideControls();

                video.setVideoURI(videoUri);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }, 500);

}
```

Please suggest me if I am doing some mistake in it.

**Comment by deepakcipl** [comment]
Hi rtoshiro,

Thank you so much.. Now its working fine in my app. The problem was that I add a line compile 'com.github.rtoshiro.fullscreenvideoview:fullscreenvideoview:1.0.+' in build.gradle as well as copy both the java Video files FullScreenVideoLayout and FullScreenVideoView in my package. So when I remove the above line it works for me. Can you please tell me Why it was not working previously ? Was it retreiving the old java files due to this compile line ?

**Comment by rtoshiro** [comment]
It's really strange compiler didn't complain about package+class name conflict.
Using gradle (compile '...') is the recommended way because when the library gets updated, gradle will update it automatically. 
If you delete java files and keep only the compile '...' command, it did not work?

**Comment by deepakcipl** [comment]
Hi rtoshiro,

I didn't try this scenario to delete the java files and put only the compile line in build.gradle. I put java files as well compile line both and due too which the problem persist but when I remove the compile line code ran perfectly fine.

**Comment by rtoshiro** [comment]
Hi @deepakcipl 
Well, the good news it that is functioning now :)
Thank you for your time.
Best
