### ISSUE TITLE
QC MediaPlayer not present

### ISSUE THREAD

**Issue by anudeepreddygopu** [rtoshiro/FullscreenVideoView#6]
Hey I am getting the error as QC MediaPlayer not present and the app crashes saring
error inflating calss com.github....

**Comment by deepakcipl** [comment]
HI Anudeep,
Install any media player app in your device and please provide the complete class name which getting error.

**Comment by rtoshiro** [comment]
Hi @anudeepreddygopu 
If you use "android.widget.VideoView", does it work?

**Comment by rtoshiro** [comment]
I'm closing it due to lack of activity.
