### ISSUE TITLE
any property for fullscreen?

### ISSUE THREAD

**Issue by uzman** [rtoshiro/FullscreenVideoView#7]
Hi,
how can i check if it is playing on fullscreen or framed size?
i want to check it if the user press back button while the video is playing in fullscreen mode.
Also i am listening the setOnCompletionListener event. when the video is finished and if its in fullscreen mode i want to go back framed size.

thanks...

**Comment by rtoshiro** [comment]
Hi @uzman 
Nice question :) i didn't remember why I didn't expose isFullscreen variable.
Well, you can access a protected variable called "isFullscreen" if you had extended FFVLayout or View. 
In fact, looking for fullscreen method now, I think it was better if the control about toggling fullscreen mode was user responsibility. 
I think I going to make fullscreen method "deprecated" and create a pair of isFullscreen() and setFullscreen(boolean) methods. 
Well. Thank you anyway.
I'll keep you in touch as soon as I implement that.
Best

**Comment by rtoshiro** [comment]
Hi @uzman 
I had released a new version with fullscreen changes.
Thank you again.
