### ISSUE TITLE
MOV support

### ISSUE THREAD

**Issue by TLHP** [rtoshiro/FullscreenVideoView#9]
It's nice if FVV supports MOV extension :)

Cheers

**Comment by rtoshiro** [comment]
Hi @TLHP 
Thank you for your feedback but FVV is intended to use native Android decoders to support most of platforms available.
Since Android doesn't suppport MOV files, FVV doesn't support it neither.
http://developer.android.com/guide/appendix/media-formats.html

Best.
T
